version: '3.3'
services:
  decadevs_docker_tolulope:
    container_name: decadevs-docker-tolulope
    image: decadevs-docker-tolulope
    build: ./
    ports:
      - "8046:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: tolulope
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password